### PR TITLE
Created PCB files in case somebody wants them. 

### PR DESCRIPTION
**Pull request by LoneWalkerWolf**
I personally don't like to have things in boxes and instead have them on a PCB.
This PR includes gerbers, BOMs and CSV files for Pick and Place. 

NOTE: This PCB has been designed for 0604 components and has some hard-to-solder SSOP packages. (not for the inexperienced solderer)

### CODE REVIEW

**Comment by sstaub** [comment]
It looks very interesting. Does your design also work with consoles? 
Which program can used for open the files, KiCad?
Is there a schematic?
It will useful to change the design to the new Mega-AVR like DA-Series, maybe DU series if available.

**Comment by LoneWalkerWolf** [comment]
It's the exact same design as "box-1" except that the Arduino is now embedded in the PCB. I have no reason as to why it wouldn't work with a console. Still waiting for the PCBs to arrive, when they do, I can test it on a console. 

Here is the schematic. It was designed in EasyEDA. 

Schematic_Lighthack_2022-04-02

In terms of Mega-AVR or DU series - I currently don't have much time on my hands, as I am booked full of shows up until August. Will try something then!

**Comment by samkearney** [comment]
Hi @LoneWalkerWolf, thanks for the contribution!

We don't have (and are currently not planning) a "canonical" PCB design for the box 1 kit, but I understand the desire to use a PCB rather than hand-wiring. Historically when accepting community contributions like this, we've put them in the top-level directory called `user_projects` (see https://github.com/ETCLabs/lighthack/pull/12). Would you be able to modify this PR to put all of your files in the folder `user_projects/box_1_pcb`? It would also be nice to put a `README.md` file inside the `box_1_pcb` folder to give a brief overview of how to use the files.

Thanks!

**Comment by LoneWalkerWolf** [comment]
Apologies for not getting back to you guys on this. 
I have created the README and have moved the files into the user_projects directory. 

I can now also confirm that the PCB does work with consoles. I have tested it on my Ion XE, XP, and my local theatre's Gio@5.

**Pull request closed without merging**
